CC = riscv64-linux-gnu-gcc
#CFLAGS = -nostdlib -fno-builtin -mcmodel=medany -march=rv32ima -mabi=ilp32
CFLAGS =-nostdlib -fno-builtin  -Wall -mcmodel=medany -g  -O0

QEMU = qemu-system-riscv64
QFLAGS = -nographic -smp 4 -machine virt -bios none


all: os.elf

os.elf: start.s sys.s lib.c os.c
	$(CC) $(CFLAGS) -T os.ld -o os.elf $^

qemu: $(TARGET)
	@qemu-system-riscv64 -M ? | grep virt >/dev/null || exit
	@echo "Press Ctrl-A and then X to exit QEMU"
	$(QEMU) $(QFLAGS) -kernel os.elf

clean:
	rm -f *.elf
